config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get "/", to: "home#index", as: :home
  post 'comments/create', to: "comments#create", as: :comments_create
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment
  attr_accessor :id, :text, :url

  def initialize(id, text, url)
    @id = id
    @text = text
    @url = url
  end
end

app/controllers/application_controller.rb
require "pry"

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(
      params[:index],
      params[:text],
      params[:url], # to associate comments to incoming api articles w/o article persistence
    )
  end
end

app/controllers/home_controller.rb
require 'news-api'

class HomeController < ApplicationController
  PER_PAGE = 10.freeze

  def index
    @page = params[:page] ? params[:page].to_i : 1
    @offset = (@page - 1) * PER_PAGE
    n = News.new("aceb7c8dcfcd407088c69ce236945039")
    @articles = n.get_everything(sources: "bbc-news")[@offset..@offset + (PER_PAGE - 1)]
    @next_page = @page + 1 if @articles.size == PER_PAGE
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_comment.html.haml
%div{style: "border: black 1px solid; margin-bottom: 50px; padding: 20px; height: 100px"}
  = comment.text

app/views/comments/create.turbo_stream.haml
= turbo_stream.append("comments-list-#{@comment.id}", partial: "comment", locals: {comment: @comment})

app/views/home/_article.html.haml
.div{style: "border: black 1px solid; margin-bottom: 50px; padding: 20px"}
  %h3
    = article.title
  %p
    = article.description
  %div
    = turbo_frame_tag "#{id}" do
      %div{style: "border: blue .5px solid; margin-top: 50px; padding: 20px"}
        %div{id:"comment-list-#{id}"}
        = form_with url: comments_create_path do |f|
          = f.text_area :text
          = f.hidden_field :index, value: id
          = f.hidden_field :url, value: article.url
          = f.submit

app/views/home/index.html.haml
%div
  %font-bold.text-4xl.text-blue-500
    Home#index
  = turbo_frame_tag "home_#{@page}" do
    - @articles.each_with_index do |article, i|
      = render "article", article: article, id: i
    - if @next_page
      = "loading..."
      = turbo_frame_tag "home_#{@next_page}", loading: :lazy, src: home_path(page: @next_page)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireNewsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>